# This docker-compose.yml is only for development environment.

version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      # You can set the value of environment variables
      # in your docker-compose.yml file
      # Our Node app will use these to connect
      # to the database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=suissdb
    ports:
      # Standard port for PostgreSQL databases
      - "5050:5432"
    
    volumes:
      - ./postgres-data:/var/lib/postgresql/data